name: GITHUB ACTION DEMO

on:
  push:
    branches:
      - main

jobs:
  Github-Actions-JobDemo-1:
    name: Exploring-Github-Actions
    runs-on: ubuntu-latest

    steps:
      - name: Display the event that triggered the workflow
        run: echo "This job was triggered by a ${{github.event_name}} event"

      - name: Display runner info
        run: echo "It is running on a(n) ${{runner.os}} server hosted by Github"

      - name: Info about the repository and branch
        run: |
          echo "The name of your branch is ${{github.ref}} and your repository is ${{github.repository}}"
          echo "The event that triggered the workflow is ${{github.event_name}}"

      - name: Use in-built GitHub actions
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for PRs

      - name: Display repository information
        run: |
          echo "The GitHub repository ${{github.repository}} has been cloned to the runner"
          echo "Your repository has been copied to the path ${{github.workspace}} on the runner"
          echo "The workflow is now ready to test your code on the runner"

      - name: Testing conditional events
        if: ${{github.event_name == 'pull_request'}}
        run: echo "This event is a pull request"

      - name: List files in the repository
        run: ls ${{github.workspace}}

      - name: Setup .NET on runner
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.x'

      - name: Display .NET version
        run: dotnet --version

      - name: Display preinstalled tools location
        run: echo "The preinstalled tools are located here on the runner ${{runner.tool_cache}}."

      - name: List files in tool cache
        run: ls ${{runner.tool_cache}}

      - name: Display job status
        run: echo "This job's status is ${{job.status}}."
